debug: true

logging:
  level:
    org.springframework: DEBUG
    com.graphene: DEBUG

graphene:
  writer:
    blacklist:
      'test':
        - '^xxx_sum.*\.system\..*'
    input:
      graphite:
        carbon:
          bind: "0.0.0.0"
          port: 2003
  #        route:
  #          host: 127.0.0.1
  #          port: 2003
      kafka:
        custom:
          enabled: false
          bootstrapServer: "localhost:9092"
          consumerGroupId: "custom-graphene-writer"
          pollIntervalMs: 5000
          maxPollRecords: 1000
          topics: "graphene-custom"
          keyDeserializerClass: "org.apache.kafka.common.serialization.StringDeserializer"
          valueDeserializerClass: "com.graphene.writer.input.kafka.deserializer.PrometheusDeserializer"
        prometheus:
          enabled: true
          bootstrapServer: "localhost:9092"
          consumerGroupId: "prometheus-graphene-writer"
          pollIntervalMs: 5000
          maxPollRecords: 1000
          topics: "graphene-prometheus"
          keyDeserializerClass: "org.apache.kafka.common.serialization.StringDeserializer"
          valueDeserializerClass: "com.graphene.writer.input.kafka.deserializer.PrometheusDeserializer"
        influx-db:
          enabled: false
          bootstrapServer: "localhost:9092"
          consumerGroupId: "influxdb-graphene-writer"
          pollIntervalMs: 5000
          maxPollRecords: 1000
          topics: "graphene-influxdb"
          keyDeserializerClass: "org.apache.kafka.common.serialization.StringDeserializer"
          valueDeserializerClass: "com.graphene.writer.input.kafka.deserializer.InfluxDbDeserializer"
    store:
      key:
        handlers:
          logging-key-store-handler:
            tenant: none
            rotation:
              strategy: "timeBasedRotation"
              period: "1d"
            handler:
              type: "LoggingKeyStoreHandler"
          simple-key-store-handler:
            tenant: none
            rotation:
              strategy: "noOpRotation"
            handler:
              type: "SimpleKeyStoreHandler"
              property:
                clusterName: "metric"
                cluster: "127.0.0.1"
                port: 9200
                userName: ""
                userPassword: ""
                protocol: "http"
                templateIndexPattern: "simple-key-path*"
                index: "simple-key-path"
                type: "path"
                bulk:
                  actions: 10000
                  interval: 500
          rotated-simple-key-store-handler:
            tenant: none
            rotation:
              strategy: "timeBasedRotation"
              period: "1w"
            handler:
              type: "SimpleKeyStoreHandler"
              property:
                clusterName: "metric"
                cluster: "127.0.0.1"
                port: 9200
                userName: ""
                userPassword: ""
                protocol: "http"
                templateIndexPattern: "simple-key-path*"
                index: "simple-key-path"
                type: "path"
                bulk:
                  actions: 10000
                  interval: 500
          index-based-key-store-handler:
            tenant: none
            rotation:
              strategy: "timeBasedRotation"
              period: "1w"
            handler:
              type: "IndexBasedKeyStoreHandler"
              property:
                clusterName: "metric"
                cluster: "127.0.0.1"
                port: 9200
                userName: ""
                userPassword: ""
                protocol: "http"
                templateIndexPattern: "index-based-key-path*"
                index: "index-based-key-path"
                type: "path"
                bulk:
                  actions: 10000
                  interval: 500
          tag-based-key-store-handler:
            tenant: none
            rotation:
              strategy: "noOpRotation"
              period: "1w"
            handler:
              type: "TagBasedKeyStoreHandler"
              property:
                clusterName: "metric"
                cluster: "127.0.0.1"
                port: 9200
                userName: ""
                userPassword: ""
                protocol: "http"
                templateIndexPattern: "tag-based-key-path*"
                index: "tag-based-key-path"
                type: "path"
                bulk:
                  actions: 10000
                  interval: 500
      data:
        handlers:
#          simple-data-store-handler:
#            type: "SimpleDataStoreHandler"
#            tenant: NONE
#            ttl: 604800
#            rollup: 60
#            keyspace: "metric"
#            columnFamily: "metric"
#            bucketSize: 0
#            property:
#              cluster:
#                - "127.0.0.1"
#              port: 9042
#              userName: "cassandra"
#              userPassword: "cassandra"
#              maxConnections: 2048
#              readTimeout: 10
#              connectTimeout: 10
#              maxRequests: 128
#              maxQueueSize: 4194304 # 4 * 1024 * 1024
#              loadBalancingPolicyName: "TokenDcAwareRoundRobinPolicy"
#              consistencyLevel: "ONE"
#              protocolVersion: "V4"
          offset-based-data-store-handler:
            type: "OffsetBasedDataStoreHandler"
            tenant: NONE
            ttl: 604800
            rollup: 60
            keyspace: "metric_offset"
            columnFamily: "metric"
            bucketSize: 30000
            property:
              cluster:
                - "127.0.0.1"
              port: 9042
              userName: "cassandra"
              userPassword: "cassandra"
              maxConnections: 2048
              readTimeout: 10
              connectTimeout: 10
              maxRequests: 128
              maxQueueSize: 4194304 # 4 * 1024 * 1024
              loadBalancingPolicyName: "TokenDcAwareRoundRobinPolicy"
              consistencyLevel: "ONE"
              protocolVersion: "V4"
    stats:
      interval: 60
      tenant: "graphene"
      hostname: "localhost"
      log: true
server:
  port: 8081
